# Generated by Django 4.1 on 2023-06-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='app_comment',
        ),
        migrations.AlterModelTable(
            name='like',
            table='app_like',
        ),
        migrations.AlterModelTable(
            name='retweet',
            table='app_retweet',
        ),
        migrations.AlterModelTable(
            name='tweet',
            table='app_tweet',
        ),
    ]
