# Generated by Django 4.1 on 2023-06-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_username_myuser_username_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username_id',
            new_name='userid',
        ),
    ]
