# Generated by Django 4.1 on 2023-06-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_username_id_myuser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='common/default.png', null=True, upload_to='images'),
        ),
    ]
